"""10032025 change field doc type

Revision ID: 002e7902b9be
Revises: 0c0d8317eb86
Create Date: 2025-03-10 15:15:21.683237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002e7902b9be'
down_revision: Union[str, None] = '0c0d8317eb86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_type', sa.Column('is_multiple', sa.Boolean(), nullable=False))
    op.add_column('doc_type', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('doc_type', 'is_doc_asal',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint('doc_type_alashak_id_fkey', 'doc_type', type_='foreignkey')
    op.drop_column('doc_type', 'alashak_id')
    op.drop_column('doc_type', 'status')
    op.drop_column('doc_type', 'is_unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_type', sa.Column('is_unit', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('doc_type', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('doc_type', sa.Column('alashak_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('doc_type_alashak_id_fkey', 'doc_type', 'alashak', ['alashak_id'], ['id'])
    op.alter_column('doc_type', 'is_doc_asal',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('doc_type', 'is_active')
    op.drop_column('doc_type', 'is_multiple')
    # ### end Alembic commands ###
