"""28 Feb 2025 16:32 fix table mapping doc type

Revision ID: 057847d43005
Revises: 243112d720c2
Create Date: 2025-02-28 16:51:03.406206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '057847d43005'
down_revision: Union[str, None] = '243112d720c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docformat_jenisarsip_doctype',
    sa.Column('doc_format_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jenis_arsip', sa.Enum('ARSIP_HOLDING', 'ARSIP_AJB', name='jenisarsipenum'), nullable=False),
    sa.ForeignKeyConstraint(['doc_format_id'], ['document_format.id'], ),
    sa.ForeignKeyConstraint(['doc_type_id'], ['document_type.id'], ),
    sa.PrimaryKeyConstraint('doc_format_id', 'doc_type_id', 'jenis_arsip')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('docformat_jenisarsip_doctype')
    # ### end Alembic commands ###
