"""4 Maret 2025 add table master

Revision ID: 153f6dd20027
Revises: 
Create Date: 2025-03-04 09:54:14.680474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '153f6dd20027'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alashak',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_alashak_id'), 'alashak', ['id'], unique=False)
    op.create_table('column_type',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipe_data', sa.Enum('ENUM', 'DATE_PICKER', 'DATE_TIME_PICKER', 'STRING', 'INTEGER', 'DECIMAL', 'BOOLEAN', name='tipedataenum'), nullable=True),
    sa.Column('enum_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('is_show', sa.Boolean(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_type_id'), 'column_type', ['id'], unique=False)
    op.create_table('departement',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_departement_id'), 'departement', ['id'], unique=False)
    op.create_table('doc_format',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('classification', sa.Enum('ARSIP_AJB', 'ARSIP_HOLDING', 'PBB', 'PBT', 'SPH_PJB_PPJB', 'SPS', 'TANDA_TERIMA_KONSUMEN_BANK', 'AJB_HOLDING', 'BPHTH', name='documentclassificationenum'), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_doc_format_id'), 'doc_format', ['id'], unique=False)
    op.create_table('doc_type_group',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_doc_type_group_id'), 'doc_type_group', ['id'], unique=False)
    op.create_table('doc_type',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('is_doc_asal', sa.Boolean(), nullable=True),
    sa.Column('is_unit', sa.Boolean(), nullable=True),
    sa.Column('alashak_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('doc_type_group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alashak_id'], ['alashak.id'], ),
    sa.ForeignKeyConstraint(['doc_type_group_id'], ['doc_type_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_doc_type_id'), 'doc_type', ['id'], unique=False)
    op.create_table('doc_archive',
    sa.Column('doc_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('doc_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doc_type_id'], ['doc_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_archive_id'), 'doc_archive', ['id'], unique=False)
    op.create_table('doc_type_archive',
    sa.Column('doc_format_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jenis_arsip', sa.Enum('ARSIP_HOLDING', 'ARSIP_AJB', name='jenisarsipenum'), nullable=False),
    sa.ForeignKeyConstraint(['doc_format_id'], ['doc_format.id'], ),
    sa.ForeignKeyConstraint(['doc_type_id'], ['doc_type.id'], ),
    sa.PrimaryKeyConstraint('doc_format_id', 'doc_type_id', 'jenis_arsip')
    )
    op.create_table('doc_type_column',
    sa.Column('doc_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('column_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['column_type_id'], ['column_type.id'], ),
    sa.ForeignKeyConstraint(['doc_type_id'], ['doc_type.id'], ),
    sa.PrimaryKeyConstraint('doc_type_id', 'column_type_id')
    )
    op.create_table('doc_archive_kolom_link',
    sa.Column('doc_archive_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('column_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['column_type_id'], ['column_type.id'], ),
    sa.ForeignKeyConstraint(['doc_archive_id'], ['doc_archive.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_archive_kolom_link_id'), 'doc_archive_kolom_link', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doc_archive_kolom_link_id'), table_name='doc_archive_kolom_link')
    op.drop_table('doc_archive_kolom_link')
    op.drop_table('doc_type_column')
    op.drop_table('doc_type_archive')
    op.drop_index(op.f('ix_doc_archive_id'), table_name='doc_archive')
    op.drop_table('doc_archive')
    op.drop_index(op.f('ix_doc_type_id'), table_name='doc_type')
    op.drop_table('doc_type')
    op.drop_index(op.f('ix_doc_type_group_id'), table_name='doc_type_group')
    op.drop_table('doc_type_group')
    op.drop_index(op.f('ix_doc_format_id'), table_name='doc_format')
    op.drop_table('doc_format')
    op.drop_index(op.f('ix_departement_id'), table_name='departement')
    op.drop_table('departement')
    op.drop_index(op.f('ix_column_type_id'), table_name='column_type')
    op.drop_table('column_type')
    op.drop_index(op.f('ix_alashak_id'), table_name='alashak')
    op.drop_table('alashak')
    # ### end Alembic commands ###
