"""28 Feb 2025 11:04 fixing table mapping doc_format doc_type jenis_arsip

Revision ID: 243112d720c2
Revises: 97763821733b
Create Date: 2025-02-28 11:18:57.581656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '243112d720c2'
down_revision: Union[str, None] = '97763821733b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docformat_jenisarsip_doctype',
    sa.Column('doc_format_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('doc_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jenis_arsip', sa.Enum('ARSIP_HOLDING', 'ARSIP_AJB', name='jenisarsipenum'), nullable=True),
    sa.ForeignKeyConstraint(['doc_format_id'], ['document_format.id'], ),
    sa.ForeignKeyConstraint(['doc_type_id'], ['document_type.id'], ),
    sa.PrimaryKeyConstraint('doc_format_id', 'doc_type_id')
    )
    op.create_table('doctype_jeniskolom',
    sa.Column('doc_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jenis_kolom_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['doc_type_id'], ['document_type.id'], ),
    sa.ForeignKeyConstraint(['jenis_kolom_id'], ['jenis_kolom.id'], ),
    sa.PrimaryKeyConstraint('doc_type_id', 'jenis_kolom_id')
    )
    op.drop_index('ix_doc_type_jenis_kolom_link_id', table_name='doc_type_jenis_kolom_link')
    op.drop_table('doc_type_jenis_kolom_link')
    op.drop_index('ix_doc_format_jenis_arsip_doc_type_link_id', table_name='doc_format_jenis_arsip_doc_type_link')
    op.drop_table('doc_format_jenis_arsip_doc_type_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_format_jenis_arsip_doc_type_link',
    sa.Column('doc_format_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('doc_type_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('jenis_arsip', postgresql.ENUM('ARSIP_HOLDING', 'ARSIP_AJB', name='jenisarsipenum'), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=26), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doc_format_id'], ['document_format.id'], name='doc_format_jenis_arsip_doc_type_link_doc_format_id_fkey'),
    sa.ForeignKeyConstraint(['doc_type_id'], ['document_type.id'], name='doc_format_jenis_arsip_doc_type_link_doc_type_id_fkey'),
    sa.PrimaryKeyConstraint('doc_format_id', 'doc_type_id', 'id', name='doc_format_jenis_arsip_doc_type_link_pkey')
    )
    op.create_index('ix_doc_format_jenis_arsip_doc_type_link_id', 'doc_format_jenis_arsip_doc_type_link', ['id'], unique=False)
    op.create_table('doc_type_jenis_kolom_link',
    sa.Column('doc_type_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('jenis_kolom_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=26), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doc_type_id'], ['document_type.id'], name='doc_type_jenis_kolom_link_doc_type_id_fkey'),
    sa.ForeignKeyConstraint(['jenis_kolom_id'], ['jenis_kolom.id'], name='doc_type_jenis_kolom_link_jenis_kolom_id_fkey'),
    sa.PrimaryKeyConstraint('doc_type_id', 'jenis_kolom_id', 'id', name='doc_type_jenis_kolom_link_pkey')
    )
    op.create_index('ix_doc_type_jenis_kolom_link_id', 'doc_type_jenis_kolom_link', ['id'], unique=False)
    op.drop_table('doctype_jeniskolom')
    op.drop_table('docformat_jenisarsip_doctype')
    # ### end Alembic commands ###
