"""25032025 wf and enum

Revision ID: 451dc7ff258c
Revises: 8ab315a965a4
Create Date: 2025-03-25 14:32:11.173274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '451dc7ff258c'
down_revision: Union[str, None] = '8ab315a965a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow',
    sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('txn_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('step_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_status', postgresql.ENUM('DRAFT', 'ISSUED', 'COMPLETED', 'REJECTED', 'NEED_DATA_UPDATE', 'WAITING_APPROVAL', name='workflowlaststatusenum', create_type=False), nullable=True),
    sa.Column('last_status_at', sa.DateTime(), nullable=True),
    sa.Column('last_step_app_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_step_app_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_step_app_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_step_app_action_at', sa.DateTime(), nullable=True),
    sa.Column('last_step_app_action_remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entity', postgresql.ENUM('MEMO', name='workflowentityenum', create_type=False), nullable=False),
    sa.Column('flow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_id'), 'workflow', ['id'], unique=False)
    op.create_table('workflow_template',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('entity', postgresql.ENUM('MEMO', name='workflowentityenum', create_type=False), nullable=True),
    sa.Column('flow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_template_id'), 'workflow_template', ['id'], unique=False)
    op.create_table('workflow_history',
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('step_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_status', postgresql.ENUM('DRAFT', 'ISSUED', 'COMPLETED', 'REJECTED', 'NEED_DATA_UPDATE', 'WAITING_APPROVAL', name='workflowlaststatusenum', create_type=False), nullable=True),
    sa.Column('last_status_at', sa.DateTime(), nullable=True),
    sa.Column('last_step_app_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_step_app_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_step_app_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_step_app_action_at', sa.DateTime(), nullable=True),
    sa.Column('last_step_app_action_remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_history_id'), 'workflow_history', ['id'], unique=False)
    op.create_table('workflow_next_approver',
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_next_approver_id'), 'workflow_next_approver', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_next_approver_id'), table_name='workflow_next_approver')
    op.drop_table('workflow_next_approver')
    op.drop_index(op.f('ix_workflow_history_id'), table_name='workflow_history')
    op.drop_table('workflow_history')
    op.drop_index(op.f('ix_workflow_template_id'), table_name='workflow_template')
    op.drop_table('workflow_template')
    op.drop_index(op.f('ix_workflow_id'), table_name='workflow')
    op.drop_table('workflow')
    # ### end Alembic commands ###
