"""4 Maret 2025 15:20 add table code counter

Revision ID: 5ceba6ffd852
Revises: 153f6dd20027
Create Date: 2025-03-04 15:26:08.282857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5ceba6ffd852'
down_revision: Union[str, None] = '153f6dd20027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_counter',
    sa.Column('entity', sa.Enum('DOC_FORMAT', 'DOC_TYPE', 'DOC_TYPE_GROUP', name='codecounterenum'), nullable=True),
    sa.Column('last', sa.Integer(), nullable=True),
    sa.Column('digit', sa.Integer(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_counter_id'), 'code_counter', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_counter_id'), table_name='code_counter')
    op.drop_table('code_counter')
    # ### end Alembic commands ###
