"""14 Maret 2025 fix field memo doc

Revision ID: 6e76c0953ed9
Revises: f933f14330e3
Create Date: 2025-03-14 11:47:49.258638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e76c0953ed9'
down_revision: Union[str, None] = 'f933f14330e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'memo_doc', 'doc_type', ['doc_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memo_doc', type_='foreignkey')
    # ### end Alembic commands ###
