"""17032025 add name field on worker

Revision ID: 8ab315a965a4
Revises: e24197288be0
Create Date: 2025-03-17 16:37:10.144316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ab315a965a4'
down_revision: Union[str, None] = 'e24197288be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_unique_constraint(None, 'worker', ['client_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worker', type_='unique')
    op.drop_column('worker', 'name')
    # ### end Alembic commands ###
