"""5 Maret 2025 13:54 change name table doc_archive_column

Revision ID: 8bf180b5cb0c
Revises: 71f33fc77543
Create Date: 2025-03-05 13:55:43.190703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8bf180b5cb0c'
down_revision: Union[str, None] = '71f33fc77543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_type_departement',
    sa.Column('doc_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('departement_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['departement_id'], ['departement.id'], ),
    sa.ForeignKeyConstraint(['doc_type_id'], ['doc_type.id'], ),
    sa.PrimaryKeyConstraint('doc_type_id', 'departement_id')
    )
    op.create_table('doc_archive_column',
    sa.Column('doc_archive_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('column_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['column_type_id'], ['column_type.id'], ),
    sa.ForeignKeyConstraint(['doc_archive_id'], ['doc_archive.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_archive_column_id'), 'doc_archive_column', ['id'], unique=False)
    op.drop_index('ix_doc_archive_kolom_link_id', table_name='doc_archive_kolom_link')
    op.drop_table('doc_archive_kolom_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_archive_kolom_link',
    sa.Column('doc_archive_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('column_type_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=26), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['column_type_id'], ['column_type.id'], name='doc_archive_kolom_link_column_type_id_fkey'),
    sa.ForeignKeyConstraint(['doc_archive_id'], ['doc_archive.id'], name='doc_archive_kolom_link_doc_archive_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='doc_archive_kolom_link_pkey')
    )
    op.create_index('ix_doc_archive_kolom_link_id', 'doc_archive_kolom_link', ['id'], unique=False)
    op.drop_index(op.f('ix_doc_archive_column_id'), table_name='doc_archive_column')
    op.drop_table('doc_archive_column')
    op.drop_table('doc_type_departement')
    # ### end Alembic commands ###
