"""26 Feb 2025 16:50 add table master arsip

Revision ID: 97763821733b
Revises: 
Create Date: 2025-02-26 16:56:12.206098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '97763821733b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alashak',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alashak_id'), 'alashak', ['id'], unique=False)
    op.create_table('document_format',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('classification', sa.Enum('ARSIP_AJB', 'ARSIP_HOLDING', 'PBB', 'PBT', 'SPH_PJB_PPJB', 'SPS', 'TANDA_TERIMA_KONSUMEN_BANK', 'AJB_HOLDING', 'BPHTH', name='documentclassificationenum'), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_format_id'), 'document_format', ['id'], unique=False)
    op.create_table('document_type_group',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_type_group_id'), 'document_type_group', ['id'], unique=False)
    op.create_table('jenis_kolom',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipe_data', sa.Enum('ENUM', 'DATE_PICKER', 'DATE_TIME_PICKER', 'STRING', 'INTEGER', 'DECIMAL', 'BOOLEAN', name='tipedataenum'), nullable=True),
    sa.Column('enum_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('is_show', sa.Boolean(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jenis_kolom_id'), 'jenis_kolom', ['id'], unique=False)
    op.create_table('document_type',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('is_doc_asal', sa.Boolean(), nullable=True),
    sa.Column('is_unit', sa.Boolean(), nullable=True),
    sa.Column('alashak_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('doc_type_group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alashak_id'], ['alashak.id'], ),
    sa.ForeignKeyConstraint(['doc_type_group_id'], ['document_type_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_type_id'), 'document_type', ['id'], unique=False)
    op.create_table('doc_format_jenis_arsip_doc_type_link',
    sa.Column('doc_format_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('doc_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jenis_arsip', sa.Enum('ARSIP_HOLDING', 'ARSIP_AJB', name='jenisarsipenum'), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doc_format_id'], ['document_format.id'], ),
    sa.ForeignKeyConstraint(['doc_type_id'], ['document_type.id'], ),
    sa.PrimaryKeyConstraint('doc_format_id', 'doc_type_id', 'id')
    )
    op.create_index(op.f('ix_doc_format_jenis_arsip_doc_type_link_id'), 'doc_format_jenis_arsip_doc_type_link', ['id'], unique=False)
    op.create_table('doc_type_jenis_kolom_link',
    sa.Column('doc_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jenis_kolom_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doc_type_id'], ['document_type.id'], ),
    sa.ForeignKeyConstraint(['jenis_kolom_id'], ['jenis_kolom.id'], ),
    sa.PrimaryKeyConstraint('doc_type_id', 'jenis_kolom_id', 'id')
    )
    op.create_index(op.f('ix_doc_type_jenis_kolom_link_id'), 'doc_type_jenis_kolom_link', ['id'], unique=False)
    op.create_table('document_arsip',
    sa.Column('doc_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('doc_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doc_type_id'], ['document_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_arsip_id'), 'document_arsip', ['id'], unique=False)
    op.create_table('doc_arsip_kolom_link',
    sa.Column('doc_arsip_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jenis_kolom_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doc_arsip_id'], ['document_arsip.id'], ),
    sa.ForeignKeyConstraint(['jenis_kolom_id'], ['jenis_kolom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_arsip_kolom_link_id'), 'doc_arsip_kolom_link', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doc_arsip_kolom_link_id'), table_name='doc_arsip_kolom_link')
    op.drop_table('doc_arsip_kolom_link')
    op.drop_index(op.f('ix_document_arsip_id'), table_name='document_arsip')
    op.drop_table('document_arsip')
    op.drop_index(op.f('ix_doc_type_jenis_kolom_link_id'), table_name='doc_type_jenis_kolom_link')
    op.drop_table('doc_type_jenis_kolom_link')
    op.drop_index(op.f('ix_doc_format_jenis_arsip_doc_type_link_id'), table_name='doc_format_jenis_arsip_doc_type_link')
    op.drop_table('doc_format_jenis_arsip_doc_type_link')
    op.drop_index(op.f('ix_document_type_id'), table_name='document_type')
    op.drop_table('document_type')
    op.drop_index(op.f('ix_jenis_kolom_id'), table_name='jenis_kolom')
    op.drop_table('jenis_kolom')
    op.drop_index(op.f('ix_document_type_group_id'), table_name='document_type_group')
    op.drop_table('document_type_group')
    op.drop_index(op.f('ix_document_format_id'), table_name='document_format')
    op.drop_table('document_format')
    op.drop_index(op.f('ix_alashak_id'), table_name='alashak')
    op.drop_table('alashak')
    # ### end Alembic commands ###
