"""12 Maret 2025 17:19  fix memo and add attachment

Revision ID: c1c2d0245871
Revises: d2e1c7016f8c
Create Date: 2025-03-12 17:19:28.353138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c2d0245871'
down_revision: Union[str, None] = 'd2e1c7016f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memo_detail', sa.Column('tipe_doc_fisik', sa.Enum('ASLI', 'DUPLIKAT', 'COPY', 'LEGALISIR', 'SALINAN', name='typedocfisikenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memo_detail', 'tipe_doc_fisik')
    # ### end Alembic commands ###
