"""10032025 remove is show

Revision ID: c99d305c6f02
Revises: 002e7902b9be
Create Date: 2025-03-10 16:03:01.781000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c99d305c6f02'
down_revision: Union[str, None] = '002e7902b9be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('column_type', 'is_show')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_type', sa.Column('is_show', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
