"""11 Maret 2025 add table company

Revision ID: cf1cd41ed820
Revises: f116d6a64d48
Create Date: 2025-03-11 15:03:37.437521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf1cd41ed820'
down_revision: Union[str, None] = 'f116d6a64d48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_table('customer',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('PERSON', 'ORGANIZATION', 'PERSON_GROUP', name='customerdevenum'), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('known_as', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('business_id_type', sa.Enum('KTP', 'NIB', 'KIA', 'PASPOR', name='jenisidentitasenum'), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('business_establishment_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('business_id_kitas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('business_id_creation_date', sa.Date(), nullable=True),
    sa.Column('business_id_valid_until', sa.Date(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sub_district', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('district', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nationality_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('place_of_birth', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('religion', sa.Enum('ISLAM', 'KRISTEN', 'KATHOLIK', 'HINDU', 'BUDDHA', 'KONGHUCU', 'UNKNOWN', name='religionenum'), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=True),
    sa.Column('marital_status', sa.Enum('BELUM_KAWIN', 'KAWIN', 'CERAI_HIDUP', 'CERAI_MATI', 'UNKNOWN', name='maritalstatusenum'), nullable=True),
    sa.Column('npwp_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('npwp_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('npwp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nitku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('handphone_number', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('handphone_number_secondary', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mailing_address_type', sa.Enum('HOME', 'OFFICE', 'COMPANY', 'WAREHOUSE', 'OTHER', 'UNKNOWN', name='addressenum'), nullable=True),
    sa.Column('mailing_other_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mailing_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mailing_sub_district', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mailing_district', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mailing_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mailing_region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mailing_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mailing_postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_customer_id'), 'customer', ['id'], unique=False)
    op.create_table('unit',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descs', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('land_area', sa.Float(), nullable=False),
    sa.Column('building_area', sa.Float(), nullable=False),
    sa.Column('indoor_area', sa.Float(), nullable=True),
    sa.Column('outdoor_area', sa.Float(), nullable=True),
    sa.Column('sales_status', sa.Integer(), nullable=True),
    sa.Column('handover_status', sa.Integer(), nullable=True),
    sa.Column('sub_group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('floor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classification_code', sa.Integer(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sub_project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_unit_id'), 'unit', ['id'], unique=False)
    op.create_table('vendor',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('fax', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_vendor_id'), 'vendor', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_id'), table_name='vendor')
    op.drop_table('vendor')
    op.drop_index(op.f('ix_unit_id'), table_name='unit')
    op.drop_table('unit')
    op.drop_index(op.f('ix_customer_id'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
