"""12 Maret 2025 change field memo

Revision ID: d2e1c7016f8c
Revises: 38f679e97ae2
Create Date: 2025-03-12 15:27:11.600335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd2e1c7016f8c'
down_revision: Union[str, None] = '38f679e97ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memo', sa.Column('attachment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('memo', 'attachment_memo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memo', sa.Column('attachment_memo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('memo', 'attachment')
    # ### end Alembic commands ###
