"""17032025 grouping code

Revision ID: e24197288be0
Revises: e05b6a07af22
Create Date: 2025-03-17 14:57:34.671305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e24197288be0'
down_revision: Union[str, None] = 'e05b6a07af22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DATA_UTAMA', 'DATA_PENDUKUNG', name='groupingdocumentenum').create(op.get_bind())
    op.add_column('doc_type', sa.Column('grouping_code', postgresql.ENUM('DATA_UTAMA', 'DATA_PENDUKUNG', name='groupingdocumentenum', create_type=False), nullable=True))
    op.sync_enum_values(
        enum_schema='public',
        enum_name='documentclassificationenum',
        new_values=['ARSIP', 'PBB', 'PBT', 'SPH_PJB_PPJB', 'SPS', 'TANDA_TERIMA_KONSUMEN_BANK', 'AJB_HOLDING', 'BPHTB'],
        affected_columns=[TableReference(table_schema='public', table_name='doc_format', column_name='classification')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='datatypeenum',
        new_values=['ENUM', 'DATE_PICKER', 'DATE_TIME_PICKER', 'STRING', 'INTEGER', 'DECIMAL', 'BOOLEAN', 'ALASHAK', 'UNIT', 'CUSTOMER', 'VENDOR'],
        affected_columns=[TableReference(table_schema='public', table_name='column_type', column_name='data_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='datatypeenum',
        new_values=['ENUM', 'DATE_PICKER', 'DATE_TIME_PICKER', 'STRING', 'INTEGER', 'DECIMAL', 'BOOLEAN'],
        affected_columns=[TableReference(table_schema='public', table_name='column_type', column_name='data_type')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='documentclassificationenum',
        new_values=['ARSIP_AJB', 'ARSIP_HOLDING', 'PBB', 'PBT', 'SPH_PJB_PPJB', 'SPS', 'TANDA_TERIMA_KONSUMEN_BANK', 'AJB_HOLDING', 'BPHTH'],
        affected_columns=[TableReference(table_schema='public', table_name='doc_format', column_name='classification')],
        enum_values_to_rename=[],
    )
    op.drop_column('doc_type', 'grouping_code')
    sa.Enum('DATA_UTAMA', 'DATA_PENDUKUNG', name='groupingdocumentenum').drop(op.get_bind())
    # ### end Alembic commands ###
