"""15042025 workflowstepenum

Revision ID: e69447d6c16d
Revises: cf315e9d92eb
Create Date: 2025-04-15 15:23:40.125939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e69447d6c16d'
down_revision: Union[str, None] = 'cf315e9d92eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ISSUED', 'SUBMITTED', 'APPROVED_1', 'RECEIVED', 'CHECKED', 'APPROVED_2', 'POSTED', name='workflowstepenum').create(op.get_bind())
    op.alter_column('land_bank', 'luas_tanah',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('land_bank', 'luas_awal',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('land_bank', 'luas_sertifikat',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'land_bank', ['code'])
    op.alter_column('workflow', 'step_name',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ISSUED', 'SUBMITTED', 'APPROVED_1', 'RECEIVED', 'CHECKED', 'APPROVED_2', 'POSTED', name='workflowstepenum'),
               existing_nullable=True,
               postgresql_using='step_name::workflowstepenum')
    op.alter_column('workflow_history', 'step_name',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ISSUED', 'SUBMITTED', 'APPROVED_1', 'RECEIVED', 'CHECKED', 'APPROVED_2', 'POSTED', name='workflowstepenum'),
               existing_nullable=True,
               postgresql_using='step_name::workflowstepenum')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_history', 'step_name',
               existing_type=sa.Enum('ISSUED', 'SUBMITTED', 'APPROVED_1', 'RECEIVED', 'CHECKED', 'APPROVED_2', 'POSTED', name='workflowstepenum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('workflow', 'step_name',
               existing_type=sa.Enum('ISSUED', 'SUBMITTED', 'APPROVED_1', 'RECEIVED', 'CHECKED', 'APPROVED_2', 'POSTED', name='workflowstepenum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'land_bank', type_='unique')
    op.alter_column('land_bank', 'luas_sertifikat',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('land_bank', 'luas_awal',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('land_bank', 'luas_tanah',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    sa.Enum('ISSUED', 'SUBMITTED', 'APPROVED_1', 'RECEIVED', 'CHECKED', 'APPROVED_2', 'POSTED', name='workflowstepenum').drop(op.get_bind())
    # ### end Alembic commands ###
