"""11 Maret 2025 add table customer, vendor, unit dll

Revision ID: f116d6a64d48
Revises: bd42672cc8c7
Create Date: 2025-03-11 13:26:37.138373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f116d6a64d48'
down_revision: Union[str, None] = 'bd42672cc8c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_table('customer',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('known_as', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('holding', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('business_id_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('npwp', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('religion', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('marital_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('handphone_num', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('telp_num', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_id'), 'customer', ['id'], unique=False)
    op.create_table('unit',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descs', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('land_area', sa.Float(), nullable=False),
    sa.Column('building_area', sa.Float(), nullable=False),
    sa.Column('indoor_area', sa.Float(), nullable=True),
    sa.Column('outdoor_area', sa.Float(), nullable=True),
    sa.Column('sales_status', sa.Integer(), nullable=True),
    sa.Column('handover_status', sa.Integer(), nullable=True),
    sa.Column('sub_group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('floor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classification_code', sa.Integer(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sub_project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_unit_id'), 'unit', ['id'], unique=False)
    op.create_table('vendor',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('fax', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_vendor_id'), 'vendor', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_id'), table_name='vendor')
    op.drop_table('vendor')
    op.drop_index(op.f('ix_unit_id'), table_name='unit')
    op.drop_table('unit')
    op.drop_index(op.f('ix_customer_id'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
